### ISSUE TITLE
Confusion about unprovable goals and `maxRuleApplicationDepth`

### ISSUE THREAD

**Issue by Kha** [JLimperg/aesop#15]
I had a buggy rule that lead to `maxRuleApplicationDepth` maxing out, which currently leads to the goal being marked as unprovable, and generating the error message
```
aesop: failed to prove the goal after exhaustive search
```
This confused me, I would not call this an exhaustive search. Should either the message be reworded or such goals be recategorized?

**Comment by JLimperg** [comment]
Indeed this should be a separate failure mode. I think there's an easy, slightly hackish fix for this which I can add. (Even without this fix, you can usually tell by how slow the editor gets. ;))

**Comment by JLimperg** [comment]
Note to self: does not apply to `maxRuleApplications` or `maxGoals`.
