### ISSUE TITLE
Better introduction in readme

### ISSUE THREAD

**Issue by lecopivo** [JLimperg/aesop#24]
I would really appreciate a nice short and to the point introduction on what aesop is, what can it do, why and when I might want to use it.

I had to chew through setting up custom list and some simp lemmas before to even get to the first feature of aesop.

Also the name "aesop" which to me is just a random collection of letters does not help. An explanation of that name would help.

Improving readme would be highly appreciated! I have a feeling aesop is something I might be interested in. Right now I'm just not motivated enough to keep reading through the rather technical readme.

**Comment by ammkrn** [comment]
Would like to echo this. To be more specific, the question I had after looking at the README was essentially "in terms of use cases and capabilities, where does this fit on the spectrum of aggressive use of `simp` (least work) and writing a custom tactic to solve something (most work)".

Also this looks really cool, thanks for sharing it with the community.

**Comment by JLimperg** [comment]
Apologies for the very long delay. I've now added an intro which describes Aesop's major features and use cases. Does that help? If not, please feel free to reopen this issue.

**Comment by lecopivo** [comment]
Much better now, thank you!
