### ISSUE TITLE
error: unknown metavariable '?_uniq.246'

### ISSUE THREAD

**Issue by astahfrom** [JLimperg/aesop#26]
The following snippet on 7c4c11fec3f01f84d009afc213951fee772cd46f produces `error: unknown metavariable '?_uniq.246'`.

```lean
theorem all_cons (P : α → Bool) (x : α) (xs : List α) (h : (x :: xs).all P)
  : P x ∧ xs.all P := by
  aesop -- simp_all [List.all] solves it 
```

This seems to mess with the pretty printing. On the command line I get:
`failed to pretty print expression (use 'set_option pp.rawOnError true' for raw representation)`.

In vscode I get:
`Error updating: Error fetching goals: Rpc error: InternalError: unknown metavariable '?_uniq.246'`.

**Comment by JLimperg** [comment]
Thanks! I've seen this error once before, but didn't have time to address it then. My current hypothesis is that when we extract the partial proof that leads to the safe goals, we (I) don't properly create/assign all metavariables which Aesop created/assigned.
