### ISSUE TITLE
Importing aesop yields "invalid environment extension, 'coe' has already been used" error

### ISSUE THREAD

**Issue by mhuisi** [JLimperg/aesop#28]
Following the instructions in the "Adding Aesop to Your Project" section of the README in a fresh project with the `leanprover/lean4:nightly-2022-10-03` nightly, importing aesop yields an `invalid environment extension, 'coe' has already been used` error.

**Comment by mhuisi** [comment]
To be clear, `lake build` succeeds, but then opening the project and subsequently `Repro.lean` using VSCode yields the error. OTOH, doing the same for a different library seems to work, e.g. `Std4` by itself.

**Comment by JLimperg** [comment]
Can't reproduce this either -- I can open `Repro.lean` in VSCode and Emacs and it typechecks without issues. My best guess is that your environment got subtly broken somehow, so I would nuke some combination of `~/.elan`, VSCode and `lean_packages` and start from scratch.

**Comment by mhuisi** [comment]
Hm. Nuking all the build directories (I had tried this by itself before) + elan unfortunately didn't resolve the issue either. Perhaps it has something to do with the fact that I'm using W10? Very strange regardless.

All my files are identical to yours.

**Comment by mhuisi** [comment]
That fixes the issue :) Compilation seems to be much quicker as well.

**Comment by Kha** [comment]
Trading compilation time for run time is the central idea, yes :) . If I had to guess, I would say that std4's `coe` extension is loaded both by the precompiled code and by interpreted .olean code. Not sure why yet, but a platform-specific bug somewhere in there is at least thinkable.

**Comment by JLimperg** [comment]
Okay, interesting. I'll mention in the README that there's a possible issue on Windows. Thanks for the report!

**Comment by tydeu** [comment]
@Kha @JLimperg  I encountered this same bug a while back myself in Alloy. The problem is with `PresistentEnvExtension`, the extensions is seen both in the precompiled shared object and by the the interpreted import which results in a clash. To get around this, when registering a persistent extension, one can check whether an extension with the same name already exists and return it instead. This is unsafe, but works. See [`findOrRegisterPersistentExtension`](https://github.com/tydeu/lean4-alloy/blob/515cfd6f47ce6adb8bb2060ccc5abbf1e22d8d40/Alloy/Util/Extension.lean#L11-L29) in Alloy for an example check and [these extensions](https://github.com/tydeu/lean4-alloy/blob/515cfd6f47ce6adb8bb2060ccc5abbf1e22d8d40/Alloy/C/Extension.lean#L14-L19) for the actual use.

As this appears to need a std4 change, it might be best to loop @digama0 into this issue and potentially create a similar issue on the std4 repository (or even to upstream this change into the Lean 4 core's environment registration).

**Comment by Kha** [comment]
Let's please fix the actual bug instead of adding workarounds.

**Comment by tydeu** [comment]
@Kha Ah, sorry, from this issue and my experience, I was under the impression it just part of how Windows loads module shared objects. I guess the idea is that there is some platform-specific problem with the Windows module load process that causes it run the initializer twice or already have the extension in the persistent environment reference map?

**Comment by Kha** [comment]
Yes, as I wrote above.

**Comment by tydeu** [comment]
@Kha Ah. I saw that issue, and while the 128 module limit problem you found was interesting, I was a little confused as to why that would be causing this bug. For example, Alloy most certainly does not have more than 128 precompiled modules so it should not be hitting that limit yet still has this problem. Maybe I should move this discussion over there then? I was posting here to give a workaround for if some really needs precompiled modules to work in the presence of this issue in the meantime (like Alloy does). I also wanted to highlight that the problem (in my experience) comes specifically from name clashes in persistent environment extension registration / map.

**Comment by Kha** [comment]
Yes, let's continue the discussion there. Any help by Windows users is appreciated.

**Comment by JLimperg** [comment]
Aesop master now uses the 11-19 Lean nightly, which contains a fix for this issue. @mhuisi could you try enabling `precompileModules` again to see whether it works now?

**Comment by mhuisi** [comment]
The language server yields 
```
error: external command `c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe` exited with code 1
``` 
when opening `Repro.lean`.
Building `Repro` from scratch yields a bunch of errors of the following form:
```
C:\Users\mhuisi\Desktop\Repro> lake build
Building Aesop.Check
Building Std.Tactic.Unreachable
Building Aesop.Nanos
Building Std.Lean.TagAttribute
Building Std.Classes.Dvd
Building Std.Tactic.OpenPrivate
Building Std.Classes.BEq
Building Std.Tactic.GuardExpr
Building Std.Tactic.SeqFocus
Building Std.Tactic.ByCases
Building Std.Tactic.TryThis
Building Std.Lean.Parser
Building Std.Lean.Meta
Building Std.Lean.Tactic
Building Std.Util.TermUnsafe
Building Std.Lean.NameMapAttribute
Building Std.Data.List.Init.Lemmas
Building Std.Util.ExtendedBinder
Building Std.Control.ForInStep.Basic
Building Std.Data.Option.Init.Lemmas
Building Std.Tactic.HaveI
Building Std.Tactic.RCases
Building Std.Lean.Command
Building Std.Data.DList
Building Std.Data.Fin.Lemmas
Building Std.Tactic.CoeExt
Building Std.Util.LibraryNote
Building Std.Tactic.SqueezeScope
Building Aesop.Percent
Building Aesop.Rule.BranchState
Building Aesop.Options
Building Aesop.Search.Expansion.Simp.Basic
Building Aesop.Tracing.Init
Compiling Std.Classes.Dvd
Compiling Std.Classes.BEq
error: > c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe -c -o .\lean_packages\std\build\ir\Std\Classes\Dvd.o .\lean_packages\std\build\ir\Std\Classes\Dvd.c -O3 -DNDEBUG
error: stderr:
uncaught exception: no such file or directory (error code: 2)
error: external command `c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe` exited with code 1
Compiling Aesop.Check
error: > c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe -c -o .\lean_packages\std\build\ir\Std\Classes\BEq.o .\lean_packages\std\build\ir\Std\Classes\BEq.c -O3 -DNDEBUG
error: stderr:
uncaught exception: no such file or directory (error code: 2)
error: external command `c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe` exited with code 1
Compiling Std.Tactic.Unreachable
Compiling Aesop.Nanos
error: > c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe -c -o .\lean_packages\aesop\build\ir\Aesop\Check.o .\lean_packages\aesop\build\ir\Aesop\Check.c -O3 -DNDEBUG
error: stderr:
uncaught exception: no such file or directory (error code: 2)
error: external command `c:\Users\mhuisi\.elan\toolchains\leanprover--lean4---nightly-2022-11-19\bin\leanc.exe` exited with code 1
Compiling Std.Tactic.OpenPrivate
[many more errors]
```

This is with the same lakefile from before (with `@[default_target]` instead of `@[defaultTarget]`) and `leanprover/lean4:nightly-2022-11-19`. The manifest reflects that it's using the versions of aesop and std4 that it should.
Just importing the most recent Std4 and trying to build it works without issues.

**Comment by Kha** [comment]
`leanc` failing must be some new, unrelated kind of regression :thinking:

**Comment by JLimperg** [comment]
I've seen these "no such file or directory" errors before when the VSCode extension compiles dependencies (on MacOS). However, I've not seen them in `lake build` or the Emacs mode before. They seemed to be transient as well, possibly some race condition.

**Comment by mhuisi** [comment]
I cannot reproduce this issue anymore on 01-10 (it may have to due with the disabled `precompileModules` on master, not sure).

**Comment by JLimperg** [comment]
Thanks for trying again! Let's see if this comes back once we turn `precompileModules` back on. (This is currently blocked on Lake).
