### ISSUE TITLE
README improvement suggestions

### ISSUE THREAD

**Issue by fpvandoorn** [JLimperg/aesop#39]
I'm reading through part of the readme carefully, and I'm noticing some things that could be improved:

* `declare_aesop_rule_sets [MyList.NonEmpty]`: I expect that most users won't immediately start declaring new rule sets, and I think it's not smart in this example, so it probably shouldn't be in the first example
* `@[aesop safe apply] theorem nonEmpty_append` seems like a very weird lemma to explain `safe`, since it's very much not safe. (And there are various examples below with weird things that you never want to do in practice - but often you acknowledge that)
* Is a multi-rule just a rule that creates multiple children to a single goal node? Is there any difference with an unsafe multi-rule that creates 2 children and 2 unsafe rules (with the same priority) that each generate one of these 2 children?
* The paragraph starting with "During the search, a goal or rapp can also become irrelevant" should probably explicitly state "We skip all nodes marked irrelevant" or something like that (assuming that is what you do).

**Comment by JLimperg** [comment]
Thank you, these are all great suggestions! I've now fixed them all (and refactored much of the Quickstart section in the process).
